# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc2c76607f30205d44ba457abe147074929d2348672f0b8fd113cb0da9df0e88207cb78109f79a60bc3804e8c7817186ff4992da93cbfafdc0c8998e78a37568

test:
  secret_key_base: 04f06110e3c16cac056adcca434b0e4988b125eb5fc22249080b70b921962950683ae24222cca3e4bdff90ef31870331d64fbc07e369e99edcc575e3bff48586

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
